### ISSUE TITLE
 X-Content-Options Header Vulnerability

### ISSUE THREAD

**Issue by Aliwamimkhan** [jetendo/jetendo#2]
Hi 
jetendo Team! 
Ali Wamim Khan here want to report a bug ! 
Vulnerability :X-Frame-Options Header Vulnerability 
Severity:Medium/High.
Afftectd Site : https://www.jetendo.com
Technical Details & Description:
The Anti-MIME-Sniffing header X-Content-Type-Options was not set to 'nosniff'. This allows older versions of Internet Explorer and Chrome to perform MIME-sniffing on the response body, potentially causing the response body to be interpreted and displayed as a content type other than the declared content type. Current (early 2014) and legacy versions of Firefox will use the declared content type (if one is set), rather than performing MIME-sniffing.
Information : 
This issue still applies to error type pages (401, 403, 500, etc) as those pages are often still affected by injection issues, in which case there is still concern for browsers sniffing pages away from their actual content type.
At "High" threshold this scanner will not alert on client or server error responses.

Solution - Fix & Patch: 
Ensure that the application/web server sets the Content-Type header appropriately, and that it sets the X-Content-Type-Options header to 'nosniff' for all web pages.
If possible, ensure that the end user uses a standards-compliant and modern web browser that does not perform MIME-sniffing at all, or that can be directed by the web application/web server to not perform MIME-sniffing
Affected urls :
GET: https://www.jetendo.com/
GET: https://www.jetendo.com/Introducing-Jetendo-CMS-to-Railo-CFML-developers-6-14312.html
GET: https://www.jetendo.com/Jetendo-CMS-Media-Kit---Logos-6-14311.html
GET: https://www.jetendo.com/Jetendo-News-3-3.html
GET: https://www.jetendo.com/Jetendo-documentation-system-is-now-part-of-the-main-project-1-2.html
GET: https://www.jetendo.com/New-Features-2-2.html
GET: https://www.jetendo.com/Recent-Articles-3-0.xml
GET: https://www.jetendo.com/Security-Advisory--User-authentication-system-allowed-login-between-subdomains-when-it-shouldn-t-have--1-1.html
GET: https://www.jetendo.com/Security-Alert-2-1.html
GET: https://www.jetendo.com/browser-compatibility/index
GET: https://www.jetendo.com/community/case-studies/index
GET: https://www.jetendo.com/community/contribute/index
GET: https://www.jetendo.com/community/overview/index
GET: https://www.jetendo.com/demo/index
GET: https://www.jetendo.com/development-software/index
GET: https://www.jetendo.com/download/index
GET: https://www.jetendo.com/download/notes/10
GET: https://www.jetendo.com/download/notes/19
GET: https://www.jetendo.com/download/notes/20
GET: https://www.jetendo.com/download/previousVersions
GET: https://www.jetendo.com/download/system-requirements
GET: https://www.jetendo.com/license/index
GET: https://www.jetendo.com/manual/view/current/0/index.html
GET: https://www.jetendo.com/member/
GET: https://www.jetendo.com/plugins/index
GET: https://www.jetendo.com/premium-services/index
GET: https://www.jetendo.com/roadmap/index
GET: https://www.jetendo.com/robots.txt
GET: https://www.jetendo.com/sitemap.xml
GET: https://www.jetendo.com/stylesheets/fontkit/stylesheet.css?zversion=112-2
GET: https://www.jetendo.com/stylesheets/style.css?zversion=84-4
GET: https://www.jetendo.com/support/forum/index
GET: https://www.jetendo.com/support/index
GET: https://www.jetendo.com/support/issue/index
GET: https://www.jetendo.com/templates/
GET: https://www.jetendo.com/themes/index
GET: https://www.jetendo.com/z/a/stylesheets/style.css?zversion=5-16
GET: https://www.jetendo.com/z/admin/
GET: https://www.jetendo.com/z/admin/admin-home/index
GET: https://www.jetendo.com/z/admin/help/index
GET: https://www.jetendo.com/z/admin/manual/view/0/index.html
GET: https://www.jetendo.com/z/admin/manual/view/1.1/documentation-template.html
GET: https://www.jetendo.com/z/admin/manual/view/1/site-manager-dashboard.html
GET: https://www.jetendo.com/z/admin/manual/view/2.1/manage-pages.html
GET: https://www.jetendo.com/z/admin/manual/view/2.2/add-edit-page.html
GET: https://www.jetendo.com/z/admin/manual/view/2.3/manage-menus.html
GET: https://www.jetendo.com/z/admin/manual/view/2.4/manage-slideshows.html
GET: https://www.jetendo.com/z/admin/manual/view/2.5/files-and-images.html
GET: https://www.jetendo.com/z/admin/manual/view/2.6/problem-link-report.html
GET: https://www.jetendo.com/z/admin/manual/view/2.7/site-options.html
GET: https://www.jetendo.com/z/admin/manual/view/2.8/video-library.html
GET: https://www.jetendo.com/z/admin/manual/view/2/content-manager.html
GET: https://www.jetendo.com/z/admin/manual/view/3.1/manage-blog-articles.html
GET: https://www.jetendo.com/z/admin/manual/view/3.2/add-edit-blog-article.html
GET: https://www.jetendo.com/z/admin/manual/view/3.3/manage-blog-comments.html
GET: https://www.jetendo.com/z/admin/manual/view/3.4/manage-blog-categories.html
GET: https://www.jetendo.com/z/admin/manual/view/3.5/add-edit-blog-category.html
GET: https://www.jetendo.com/z/admin/manual/view/3.6/manage-blog-tags.html
GET: https://www.jetendo.com/z/admin/manual/view/3.7/add-edit-blog-tag.html
GET: https://www.jetendo.com/z/admin/manual/view/3/blog.html
GET: https://www.jetendo.com/z/admin/manual/view/4.1/manage-leads.html
GET: https://www.jetendo.com/z/admin/manual/view/4.10/search-engine-keyword-lead-report.html
GET: https://www.jetendo.com/z/admin/manual/view/4.2/add-edit-lead.html
GET: https://www.jetendo.com/z/admin/manual/view/4.3/manage-lead-types.html
GET: https://www.jetendo.com/z/admin/manual/view/4.4/add-edit-lead-type.html
GET: https://www.jetendo.com/z/admin/manual/view/4.5/manage-lead-template-emails.html
GET: https://www.jetendo.com/z/admin/manual/view/4.6/add-edit-lead-template-email.html
GET: https://www.jetendo.com/z/admin/manual/view/4.7/export-all-leads-as-csv.html
GET: https://www.jetendo.com/z/admin/manual/view/4.8/lead-source-report.html
GET: https://www.jetendo.com/z/admin/manual/view/4.9/mailing-list-export.html
GET: https://www.jetendo.com/z/admin/manual/view/4/leads.html
GET: https://www.jetendo.com/z/admin/manual/view/5.1/manager-users.html
GET: https://www.jetendo.com/z/admin/manual/view/5.2/add-edit-user.html
GET: https://www.jetendo.com/z/admin/manual/view/5.3/import-users.html
GET: https://www.jetendo.com/z/admin/manual/view/5.4/manage-offices.html
GET: https://www.jetendo.com/z/admin/manual/view/5.5/add-edit-office.html
GET: https://www.jetendo.com/z/admin/manual/view/5/users.html
GET: https://www.jetendo.com/z/admin/manual/view/6.1/manage-listings.html
GET: https://www.jetendo.com/z/admin/manual/view/6.2/add-new-listing.html
GET: https://www.jetendo.com/z/admin/manual/view/6.3/listing-research-tool.html
GET: https://www.jetendo.com/z/admin/manual/view/6.4/listing-search-filter.html
GET: https://www.jetendo.com/z/admin/manual/view/6.5/managed-saved-searches.html
GET: https://www.jetendo.com/z/admin/manual/view/6/listings.html
GET: https://www.jetendo.com/z/blog/
GET: https://www.jetendo.com/z/content/
GET: https://www.jetendo.com/z/javascript/jetendo-init.js
GET: https://www.jetendo.com/z/listing/
GET: https://www.jetendo.com/z/misc/diagonal/
GET: https://www.jetendo.com/z/misc/diagonal/index
GET: https://www.jetendo.com/z/misc/images-security/
GET: https://www.jetendo.com/z/misc/inquiry/
GET: https://www.jetendo.com/z/misc/inquiry/index
GET: https://www.jetendo.com/z/misc/mortgage-calculator/
GET: https://www.jetendo.com/z/misc/mortgage-calculator/index
GET: https://www.jetendo.com/z/misc/mortgage-quote/
GET: https://www.jetendo.com/z/misc/mortgage-quote/index
GET: https://www.jetendo.com/z/misc/search-site/
GET: https://www.jetendo.com/z/misc/search-site/index
GET: https://www.jetendo.com/z/misc/share-with-friend/
GET: https://www.jetendo.com/z/misc/share-with-friend/index
GET: https://www.jetendo.com/z/misc/site-map/index
GET: https://www.jetendo.com/z/misc/system/
GET: https://www.jetendo.com/z/misc/system/index
GET: https://www.jetendo.com/z/misc/thank-you/
GET: https://www.jetendo.com/z/misc/thank-you/index
GET: https://www.jetendo.com/z/misc/walkscore/
GET: https://www.jetendo.com/z/misc/walkscore/index
GET: https://www.jetendo.com/z/rental/
GET: https://www.jetendo.com/z/server-manager/
GET: https://www.jetendo.com/z/server-manager/?zIsMemberArea=0&zRememberLogin=1&z_tmppassword2=ZAP&z_tmpusername2=ZAP
GET: https://www.jetendo.com/z/stylesheets/zOS.css?zversion=4-34
GET: https://www.jetendo.com/z/user/
GET: https://www.jetendo.com/zcache/zsystem.css?zv=20151207002505
GET: https://www.jetendo.com/zretsphotos/
POST: https://www.jetendo.com/z/blog/blog/addComment?blog_id=1
POST: https://www.jetendo.com/z/blog/blog/addComment?blog_id=2
POST: https://www.jetendo.com/z/server-manager/
Well, thanks for your attention, II wait more information about this report.
Thanks and best regards,
Wamim

**Comment by brucekirkpatrick** [comment]
Thanks, I added this to the nginx config for the jetendo-server project and verified it works.
	add_header X-Content-Type-Options nosniff always;
