### ISSUE TITLE
XSS in jetendo.com

### ISSUE THREAD

**Issue by amanmahendra00** [jetendo/jetendo#26]
Hey I have found a high risk security vulnerability in your website

Here is the vulnerable link
https://www.jetendo.com/z/user/reset-password/index/%22'--!%3E%3C/Title/%3C/Style/%3C/Script/%3C/Textarea/%3C/Noscript/%3C/Pre/%3C/Xmp%3E%3CSvg%20/Onload=confirm%60OPENBUGBOUNTY%60%3E

my email-amanmahendra00@gmail.com

**Comment by brucekirkpatrick** [comment]
OK, thanks.  I modified our application and that url is no longer effective.

**Comment by amanmahendra00** [comment]
Any reward?
